sudo: required
services:
    - docker

before_install:
    - docker build -t mayankgupta0510/docker-reactmyi -f Dockerfile.dev .

script:
    - docker run mayankgupta0510/docker-reactmyi npm run test -- --coverage
